name: Gradle Build

on:
  pull_request_target:
    types: [ opened, reopened, synchronize ]


jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    permissions:
      contents: read
      packages: write

    steps:
      - name: echo test
        run: echo ${{ secrets.SECRET_TEST }}

      - name: echo CHNAGED
        run: echo ${{ secrets.SECRET_TEST }}

      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
